project:
  type: website
  output-dir: ../docs

website:

  favicon: profile.jpg
  image: profile.jpg
  twitter-card: true
  title: "Ivan Jacobs"
  google-analytics: "G-LER7N2QH22"
  open-graph: true
  site-url: https://ivanjacobs.github.io/
  description: "Ivan Jacobs blog"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/IvanJac20353450
      - icon: linkedin
        href: https://www.linkedin.com/in/ivanjacobs/
      - icon: github
        href: https://github.com/ivanjacobs
format:
  html:
    theme: lumen
    css: styles.css
    self_contained: false
include-in-header:
  text: <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1978047478119932"
     crossorigin="anonymous"></script>
editor: visual

